steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure pay as you go subscription(536e7fb0-2ead-4833-bd2c-c8bcf1fc41a7)'
    KeyVaultName: 'CIPipelineKeyVault'
    SecretsFilter: '*'
    RunAsPreJob: true

jobs:
- job: MacOS
  strategy:
    matrix:
      mac:
        imageName: 'macOS-10.14'
  pool:
    vmImage: $(imageName)
  steps:
    - template: ci/macos.yml

#- job: Windows
#  strategy:
#    matrix:
#      mac:
#        imageName: 'vs2017-win2016'
#  pool:
#    vmImage: $(imageName)
#  steps:
#    - template: ci/windows.yml

# coming soon
#- job: Linux
#  strategy:
#    matrix:
#      mac:
#        imageName: 'vs2017-win2016'
#  pool:
#    vmImage: $(imageName)
#  steps:
#    - template: ci/linux.yml