# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- script: | 
    echo Hello, Azure agent is now building from pipeline!
    pwd
    ls -l
    cd Crypto_QML_GUI
    mkdir build
    cd build
    pwd
    ls -l
    qmake ../Crypto_QML_GUI.pro
    pwd
    ls -l
    make
    ls -l
  displayName: 'Creating necessary build environment...!'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Build Process...!'
