# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default
  demands:
  - agent.os -equals Darwin

steps:
- script: | 
    echo Hello, Azure agent is now building from pipeline!
    cd Crypto_QML_GUI
    mkdir build
    cd build
    qmake ../Crypto_QML_GUI.pro
    make
  displayName: 'Creating necessary build environment...!'

- task: SquishTask@1
  inputs:
    squishFolder: '/Applications/Squish for Qt 6.7.1/bin'
    squishTestSuites: '/Users/ghkraju/Documents/Projects/Qt_QML_GUI/TestSuite/suite_QML_GUI'
    squishReportGenStdout: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Crypto_QML_GUI/build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'd9e18571-4868-4836-a3ec-5f9dd2594d30'
    vstsFeedPackagePublish: 'crypto_qml_gui'
    versionOption: 'minor'